### ISSUE TITLE
This is Modula-3, people confuse it as Modula-2. Please rename.

### ISSUE THREAD

**Issue by trijezdci** [textmate/modula.tmbundle#1]
This grammar describes Modula-3 and people are confusing it as Modula-2.

For example, there is a Modula-2 atom repo on github which states that it was derived from this one and it also describes Modula-3, not Modula-2. Other people then forked that thinking it is Modula-2.

You should consider renaming to modula3.tmbundle.

**Comment by infininight** [comment]
Fixed, thanks!
